server:
  port: 8070

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/session_service_db
    username: asmaa
    password: asmaa
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: asmaa
    password: asmaa
